name: "Tracking: Protocol update to ..."
description: "Track a protocol update across all XMTP SDKs"
body:
  - type: markdown
    attributes:
      value: |
        This change is complete when it has been implemented in all our SDKs:
          - [ ] [xmtp-js](https://github.com/xmtp/xmtp-js) Link to tracking issue
          - [ ] [xmtp-ios](https://github.com/xmtp/xmtp-ios) Link to tracking issue
          - [ ] [xmtp-android](https://github.com/xmtp/xmtp-android) Link to tracking issue
          - [ ] [xmtp-flutter](https://github.com/xmtp/xmtp-flutter) Link to tracking issue
          - [ ] Update [PROTOCOL.md](https://github.com/xmtp/proto/blob/main/PROTOCOL.md) if necessary
