name: Dart dry run
on:
  push:
    branches:
      - ea/upgrade-setup-dart
jobs:
  dart:
    # https://dart.dev/tools/pub/automated-publishing
    name: Dry run (dart)
    permissions:
      id-token: write # This is required for requesting the JWT
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Setup Dart SDK with JWT token https://github.com/dart-lang/setup-dart/blob/77b84bec90e9a0d07f68a3cedd3651ba9e606a12/.github/workflows/publish.yml#L33
      - uses: dart-lang/setup-dart@a57a6c04cf7d4840e88432aad6281d1e125f0d46
      - run: dart pub get
        working-directory: ./dart
      - run: dev/dart/generate
      - run: dart test
        working-directory: ./dart
      - name: Set Tag
        run: |
          TAG=`echo $(git describe --tags --abbrev=0)`
          echo "GIT_TAG=${TAG#v}" >> $GITHUB_ENV
      - name: Prepublish
        env:
          RELEASE_VERSION: ${{ env.GIT_TAG }}
        run: dev/dart/prepublish
      - name: Verify pubspec
        run: cat ./dart/pubspec.yaml
      - name: Publish
        run: dart pub publish --dry-run
        working-directory: ./dart
