name: Lint
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  proto:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v1

      - name: run protolint
        uses: plexsystems/protolint-action@v0.7.0
        with:
          configDirectory: .
          srcDirectory: ./proto
  go:
    name: Lint (Go)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17.8" # The Go version to download (if necessary) and use.
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45.2
          args: --timeout=5m
