name: Post Release
on:
  release:
    types: [published]
jobs:
  kotlin:
    name: Release (Kotlin)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Generate protobufs
      run: dev/kotlin/generate
    - name: Run build with Gradle Wrapper
      run: ./gradlew build
    - name: Gradle Publish
      env:
        RELEASE_VERSION: ${{ github.ref_name }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
      run: ./gradlew publish