name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  js:
    name: Test (JS)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: sudo npm test
