name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  dart:
    name: Test (dart)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
      - run: dart pub get
        working-directory: ./dart
      - run: dev/dart/generate
      - run: dart test
        working-directory: ./dart
  js:
    name: Test (JS)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm test
